### ISSUE TITLE
Introducing ReactPlay section to improve.

### ISSUE THREAD

**Issue by atapas** [reactplay/docs#10]
Visit https://react-play-docs.netlify.app/intro and an introduction to react play page will be open and need to improve that page by adding more details about react play.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59080942/221353842-961f6db6-5c4d-4547-a9fb-28e2c8bc72eb.png">

Please refer these links to know more about react play
- https://github.com/reactplay/react-play#readme
- https://blog.reactplay.io/introducing-reactplay-learn-create-share-reactjs-projects

**Comment by Sachin-chaurasiya** [comment]
> Hi @Sachin-chaurasiya I would like to take this up.

Hello @supminn, I have assigned a few issues to you, so once those finish, you can take it p.

**Comment by joypoddar** [comment]
Hello @Sachin-chaurasiya , I know I have skipped a step and already worked on this issue (by creating a duplicate issue and the subsequent PR), could you assign me to this issue?

**Comment by Sachin-chaurasiya** [comment]
> Hello @Sachin-chaurasiya , I know I have skipped a step and already worked on this issue (by creating a duplicate issue and the subsequent PR), could you assign me to this issue?

Hey @joypoddar , I have assigned the issue to you.

**Comment by joypoddar** [comment]
@Sachin-chaurasiya I have added a subheading in the intro doc. 

![image](https://user-images.githubusercontent.com/11984043/230561360-1897c5dd-16c6-4589-97a1-18e45910347d.png)

What should the next steps be? Should I reopen the issue ?
