### ISSUE TITLE
Add ReactPlay website link in the navbar

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [reactplay/docs#18]
Currently, there is no way to navigate to react play website from the doc site, so add the [ReactPlay](https://reactplay.io/) link to the doc site in the navbar.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59080942/221357519-3f4f751a-7853-45ae-a6aa-f70d8cc3074f.png">

**Comment by Susmita-Dey** [comment]
I wanna take this issue

**Comment by Sachin-chaurasiya** [comment]
@Susmita-Dey , assigned to you.

**Comment by Susmita-Dey** [comment]
Hello @Dipakmali100 I was busy with my internship. But now I'm working on this issue. Please take a look into other issues.
