### ISSUE TITLE
Add get started steps in readme

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [reactplay/docs#2]
Update the [README](https://github.com/reactplay/docs/blob/main/README.md) with getting started with the project steps.

**Comment by Misterr-H** [comment]
@Sachin-chaurasiya 
hello, do we have to write starting project steps in getting started?
example: git clone repo
cd dir
npm install
npm start

**Comment by Sachin-chaurasiya** [comment]
Yes @Misterr-H , as we are using the https://docusaurus.io/, so we have to write getting started steps according to that.

**Comment by mohith2883** [comment]
Hey, @Sachin-chaurasiya 
 I would like to work on this can you assign me . Thanks! :)

**Comment by Misterr-H** [comment]
@Sachin-chaurasiya 
okay, i'll figure it out and write

**Comment by Misterr-H** [comment]
btw @mohith2883 seems more enthusiast to work upon it.

**Comment by Sachin-chaurasiya** [comment]
@Misterr-H @mohith2883, Let me know, I can assign this issue to both of and you can collaborate and work on the same.

**Comment by Misterr-H** [comment]
i'm okay with it, 
@mohith2883 lets collab

**Comment by mohith2883** [comment]
Hey @Misterr-H let's do it

**Comment by Misterr-H** [comment]
@Sachin-chaurasiya 
Please assign

**Comment by Misterr-H** [comment]
woohoo
@mohith2883 please dm

**Comment by Sachin-chaurasiya** [comment]
@Misterr-H @mohith2883 , Assigned to both of you! keep hacking.

**Comment by Misterr-H** [comment]
hello @Sachin-chaurasiya 
<img width="512" alt="Screenshot 2022-10-02 at 1 27 17 PM" src="https://user-images.githubusercontent.com/55010619/193444031-5011adc4-664d-43c4-9791-669091232470.png">

is this good?

**Comment by Sachin-chaurasiya** [comment]
@Misterr-H , Can we use code block for commands?

```shell
npm install
```

**Comment by mohith2883** [comment]
> woohoo @mohith2883 please dm

sorry bro i didn't see

**Comment by Sachin-chaurasiya** [comment]
@Misterr-H , You can refer this https://github.com/reactplay/react-play#readme

**Comment by Misterr-H** [comment]
@mohith2883 
hs913271@gmail.com

mail me

**Comment by Misterr-H** [comment]
@Sachin-chaurasiya 
like this??
<img width="514" alt="Screenshot 2022-10-02 at 1 55 08 PM" src="https://user-images.githubusercontent.com/55010619/193445104-2921a527-77bc-459d-8b0e-eb8a33f77079.png">

**Comment by Sachin-chaurasiya** [comment]
@Misterr-H , You can open a PR, I will review the changes there.

**Comment by Misterr-H** [comment]
okay sure. please wait some a minute, i'm mentoring @mohith2883 for some changes

**Comment by Sachin-chaurasiya** [comment]
> okay sure. please wait some a minute, i'm mentoring @mohith2883 for some changes

Sure, @Misterr-H , No hurries :)

**Comment by Misterr-H** [comment]
@Sachin-chaurasiya hey, we have opened the pull request
And don't forget to add label hacktoberfest-accepted while merging the PR

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya hey, we have opened the pull request
> And don't forget to add label hacktoberfest-accepted while merging the PR

Yes, sir.

**Comment by mohith2883** [comment]
@Sachin-chaurasiya  will i be counted ?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya  will i be counted ?
> 

Hey @mohith2883 ,
Your contribution will be counted for this repository but not sure about the hacktoberfest.

**Comment by mohith2883** [comment]
@Sachin-chaurasiya do you want any changes in the README

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya do you want any changes in the README 

I will review the PR and If any will request the changes.

**Comment by Misterr-H** [comment]
hello @Sachin-chaurasiya 
Since Mohith is a newbee to open source and haven't done his first PULL Request yet.
I request you to assign him some more changes in Readme.md so that he can do accordingly and do a PR.
Thankyou
Open Source for All❤️

**Comment by Misterr-H** [comment]
@Sachin-chaurasiya haven't merged Pull Request yet

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya haven't merged Pull Request yet

@Misterr-H , The review process will take some time, have some patience.

**Comment by Misterr-H** [comment]
okay @Sachin-chaurasiya .
