### ISSUE TITLE
✨ [Feature request]: Add ReactPlay discord link in navbar

### ISSUE THREAD

**Issue by edsondsouza** [reactplay/docs#26]
### Is your feature request related to a problem? Please describe.

I am frustrated when I do not find the required link. Say, for example, I know that a particular community has a discord server but it is difficult to find the link in most of the cases.

### Describe the solution you'd like.

adding a discord server link in the navbar will help developers to jump right into the server.

### Describe alternatives you've considered.

This would help beginners to redirect to the discord server instead of searching here and there for the link

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArslanYM** [comment]
Can I work on this issue?

**Comment by edsodz** [comment]
Let's go @ArslanYM 🚀

**Comment by Sachin-chaurasiya** [comment]
@edsondsouza , thanks for creating the issue, however we do have discord link in footer so we don’t need to have same link on in the navbar.
