### ISSUE TITLE
Typo in ISSUE_TEMPLATE/feature-req.yml

### ISSUE THREAD

**Issue by joypoddar** [reactplay/docs#29]
there is a typo in the screenshot question in the above file. _healps_ is the word.
![image](https://user-images.githubusercontent.com/11984043/226161351-43f26fd0-faee-43df-ac7a-889111e8a460.png)

**Comment by Sachin-chaurasiya** [comment]
Hello @joypoddar , thanks for the PR.

It would be great if you could get the issue assigned first and then start working on the changes.

I would recommend reading the contribution guidelines.
