### ISSUE TITLE
Improving the write-up on 'What is ReactPlay?' page.

### ISSUE THREAD

**Issue by joypoddar** [reactplay/docs#30]
I thought the present write-up about _What is ReactPlay?_ could be improved to capture the essence of what ReactPlay is at its core.
With this issue, I seek to work on improving the write-up.

**Comment by supminn** [comment]
Hi @joypoddar 
isn't this issue a duplicate for https://github.com/reactplay/docs/issues/10?

**Comment by Sachin-chaurasiya** [comment]
Hello @joypoddar , before creating an issue please check existing issues.

I would recommend reading the contribution guidelines.
Thanks.

**Comment by joypoddar** [comment]
> Hi @joypoddar isn't this issue a duplicate for #10?

@supminn Yes, it is.

@Sachin-chaurasiya I did identify where I went wrong. Sincere apologies for the inconvenience caused.

**Comment by Sachin-chaurasiya** [comment]
> > Hi @joypoddar isn't this issue a duplicate for #10?
> 
> @supminn Yes, it is.
> 
> @Sachin-chaurasiya I did identify where I went wrong. Sincere apologies for the inconvenience caused.

No worries, @joypoddar.

**Comment by Sachin-chaurasiya** [comment]
duplicate of #10
