### ISSUE TITLE
🐛 [Bug report]: Footer Guide Link is broken

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [reactplay/docs#35]
### Descrcibe the bug?

The guides link in the footer is broken and redirects to https://react-play-docs.netlify.app/docs/intro ( this route does not exist).

### Steps to reproduce the bug?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59080942/226807475-b097008b-8940-4d98-9438-0006731c10cf.png">

### Expected behavior

It should redirect to `https://react-play-docs.netlify.app/` instead if `https://react-play-docs.netlify.app/docs/intro`

### Desktop (Please provide your system information)

Browser [e.g. chrome]
Version [e.g. 113+]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArslanYM** [comment]
Can  I fix this issue?

**Comment by Sachin-chaurasiya** [comment]
> Can I fix this issue?

@ArslanYM , Thanks for your interest but it would great if you start working on the issue once it's assigned to you.

**Comment by ArslanYM** [comment]
@Sachin-chaurasiya  Sure will keep that in mind next time.
