### ISSUE TITLE
✨ [Feature request]: Add LinkedIn link in the footer community section

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [reactplay/docs#36]
### Is your feature request related to a problem? Please describe.

In the footer community section, we have Twitter and discord links, however, the LinkedIn link is missing, we should add the LinkedIn link.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/59080942/226808204-fe5a7c92-7ca4-4fef-a16f-7742405f428b.png">

### Describe the solution you'd like.

Add the LinkedIn link in the footer community section.

Here is the LinkedIn link --> https://www.linkedin.com/company/reactplay/

### Describe alternatives you've considered.

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArslanYM** [comment]
Can I work on this?

**Comment by Sachin-chaurasiya** [comment]
> Can I work on this?

@ArslanYM , Assigned to you.
