### ISSUE TITLE
🐛 [Bug report]:  Typo in Code of readme.md

### ISSUE THREAD

**Issue by ArslanYM** [reactplay/docs#40]
### Descrcibe the bug?

change from "massage" to " message"

### Steps to reproduce the bug?

go to Readme.md

### Expected behavior

-

### Desktop (Please provide your system information)

-

### Mobile (Please provide your device information)

-

### Screenshot / Screenshare

![issue-react-play](https://user-images.githubusercontent.com/104521101/226826922-5d8131de-578a-400e-ad3a-e82be262aa64.png)

### Relevant log output

```shell
-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by VladJav** [comment]
Can I work on this issue?

**Comment by Sachin-chaurasiya** [comment]
> Can I work on this issue?

Assigned to you @VladJav .
