### ISSUE TITLE
🐛 [Bug report]: PR #38 not reflecting on the webapp

### ISSUE THREAD

**Issue by ArslanYM** [reactplay/docs#43]
### Descrcibe the bug?

The web app should now have a linkedin link in the footer after the mergin of PR #38  but it is not so. 

### Steps to reproduce the bug?

-

### Expected behavior

-

### Desktop (Please provide your system information)

-

### Mobile (Please provide your device information)

-
![f](https://user-images.githubusercontent.com/104521101/226858622-edec75dd-b175-4846-98b9-8f6a06dd3b37.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArslanYM** [comment]
@Sachin-chaurasiya i think removing the linkedin link details like you asked me to removed it because #38 
 was already merged at the time.

**Comment by Sachin-chaurasiya** [comment]
@ArslanYM , That's why I mentioned do not mix the PR changes.
Can you raise a patch for it?

**Comment by ArslanYM** [comment]
sure

**Comment by ArslanYM** [comment]
Fixed by #45
