### ISSUE TITLE
🐛 [Bug report]: Create Play doc is not up-to-date

### ISSUE THREAD

**Issue by atapas** [reactplay/docs#46]
### Descrcibe the bug?

Here it is in its current state: https://deploy-preview-34--react-play-docs.netlify.app/How-To-Guides/how-to-create-play

We need to port this content: https://github.com/reactplay/react-play/blob/main/CREATE-PLAY.md

### Steps to reproduce the bug?

The content in the Create Play guide is not up-to-date.

### Expected behavior

It should have this content: https://github.com/reactplay/react-play/blob/main/CREATE-PLAY.md

### Desktop (Please provide your system information)

All

### Mobile (Please provide your device information)

All

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by supminn** [comment]
Hi @atapas I would like to take this up. Could you please assign this issue to me?
