### ISSUE TITLE
✨ [Feature request]: Map the docsite

### ISSUE THREAD

**Issue by atapas** [reactplay/docs#47]
### Is your feature request related to a problem? Please describe.

The doc site should be mapped to docs.reactplay.io

### Describe the solution you'd like.

- Create the subdomain and map in Netlify

### Describe alternatives you've considered.

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sachin-chaurasiya** [comment]
Completed.
