### ISSUE TITLE
✨ [Feature request]: Add doc for how to contribute 

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [reactplay/docs#50]
### Is your feature request related to a problem? Please describe.

We are getting great contributions, however, one common question we get asked is "How to contribute".

### Describe the solution you'd like.

Add a doc for "How to contribute", which provides step by step guide for contributing to this site.

### Describe alternatives you've considered.

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joypoddar** [comment]
@Sachin-chaurasiya I am interested in taking this up.

**Comment by ArslanYM** [comment]
@joypoddar What is your status on this feature?

**Comment by joypoddar** [comment]
> @joypoddar What is your status on this feature?

Working on it... Will update today..

**Comment by joypoddar** [comment]
@Sachin-chaurasiya Will we cover the contribution to `react-play` or should it contain a general take on contribution

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Will we cover the contribution to `react-play` or should it contain a general take on contribution

@joypoddar , We want to cover both for docs and reactplay repo

So create a **Contribute** directly inside the docs folder and there we will have two file
1. contribute to reactplay 
2. contribute to docs

For reference [how-to-guide]([this](https://github.com/reactplay/docs/tree/main/docs/How-To-Guides)) section

**Comment by atapas** [comment]
> > @Sachin-chaurasiya Will we cover the contribution to `react-play` or should it contain a general take on contribution
> 
> @joypoddar , We want to cover both for docs and reactplay repo
> 
> So create a **Contribute** directly inside the docs folder and there we will have two file
> 
> 1. contribute to reactplay
> 2. contribute to docs
> 
> For reference how-to-guide section

All ReactPlay related contributions.
