### ISSUE TITLE
🐛 [Bug report]: Unable to view language options in mobile view

### ISSUE THREAD

**Issue by supminn** [reactplay/docs#68]
### Descrcibe the bug?

- The following options that are available on the header are viewable only on desktop screens.

![image](https://github.com/reactplay/docs/assets/30731236/ed91494d-6fd5-4bd5-80f9-a526ee783694)

### Steps to reproduce the bug?

If you visit https://react-play-docs.netlify.app/ on your desktop, you can see these options.
However, if you view the same website using mobile devices, there is no way to access these links.

### Expected behavior

- These options are to be made available in the side panel.

### Desktop (Please provide your system information)

- We can access links to Blog, Guide, and ReactPlay on desktop
- We have the option to change the language 

![image](https://github.com/reactplay/docs/assets/30731236/13cb9473-a3a8-47d9-bf1f-ca2405fdc394)

### Mobile (Please provide your device information)

- These options are not available on mobile view

![image](https://github.com/reactplay/docs/assets/30731236/7fc9d108-60f9-4ed2-8a94-f1dbfb33efd1)

### Screenshot / Screenshare

![image](https://github.com/reactplay/docs/assets/30731236/fd9abb42-10d4-468b-8e2d-f84d914b8d5a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abhishek-90** [comment]
Hello @supminn, When you are on mobile device, kindly click on the top option in sidebar, the one with `Back to main menu` the header options are available inside.

**Comment by supminn** [comment]
Thanks for the clarification @Abhishek-90 
Marking this issue closed.
